// src/api/alerts.ts
import { fetchAlertsFromPostgres } from "./postgres/client";

/**
 * createAlert
 * - Now handled by backend logic (server-side)
 * - Kept for compatibility but logs warning
 */
export async function createAlert(alert: any) {
  console.warn("createAlert called on client - alerts should be generated by backend logic");
  return { ok: true };
}

/**
 * fetchRecentAlerts
 */
export async function fetchRecentAlerts(limitCount = 50) {
  try {
    return await fetchAlertsFromPostgres();
  } catch (err) {
    console.warn("fetchRecentAlerts error:", err);
    return [];
  }
}
